name: CI - test
on:
  repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout by SHA
      uses: actions/checkout@v2
    - run: echo {{ github.event.client_payload }}
    - run: echo {{ github.event.client_payload.sha }}
    - run: echo {{ github.event.event_type }}
